import com.sun.net.httpserver.HttpServer;   // Built-in JDK HTTP server
import com.sun.net.httpserver.HttpHandler;  // Interface for handling HTTP requests
import com.sun.net.httpserver.HttpExchange; // Represents an HTTP request-response exchange

import java.io.IOException;      // For handling IO exceptions
import java.io.OutputStream;     // For writing the response body
import java.net.InetSocketAddress; // For specifying the server address and port

// Mock server to simulate the SimpleServlet behavior without needing Tomcat
public class MockServletServer {

    public static void main(String[] args) throws IOException { // Main method to start the server
        HttpServer server = HttpServer.create(new InetSocketAddress(8888), 0); // Creating server on port 8888

        // Mapping the /App/hello endpoint — mimics @WebServlet("/hello") deployed under /App
        server.createContext("/App/hello", new HttpHandler() {
            @Override
            public void handle(HttpExchange exchange) throws IOException { // Handling incoming requests
                // Building the same HTML response as SimpleServlet.doGet()
                String htmlResponse = "<html>"
                        + "<head><title>My First Servlet</title></head>"
                        + "<body>"
                        + "<h1>Hello, Welcome to Java Servlets!</h1>"
                        + "<p>This web page was dynamically generated by the server.</p>"
                        + "</body>"
                        + "</html>";

                exchange.getResponseHeaders().set("Content-Type", "text/html"); // Setting content type
                exchange.sendResponseHeaders(200, htmlResponse.length());       // Sending 200 OK with content length
                OutputStream os = exchange.getResponseBody();                   // Getting the output stream
                os.write(htmlResponse.getBytes());                              // Writing the HTML response
                os.close();                                                     // Closing the stream
            }
        });

        server.setExecutor(null); // Using the default executor (single-threaded)
        server.start();           // Starting the HTTP server

        System.out.println("Mock Servlet Server is running...");
        System.out.println("Open in browser: http://localhost:8888/App/hello");
        System.out.println("Press Ctrl+C to stop the server.");
    }
}
