import java.io.IOException; // For handling IO exceptions during stream writing
import java.io.PrintWriter; // For writing formatted representations of objects to a text-output stream
import javax.servlet.ServletException; // For handling Servlet specific exceptions
import javax.servlet.annotation.WebServlet; // Annotation to define URL mapping
import javax.servlet.http.HttpServlet; // Base class for HTTP servlets
import javax.servlet.http.HttpServletRequest; // Interface providing request information for HTTP servlets
import javax.servlet.http.HttpServletResponse; // Interface providing HTTP-specific functionality in sending a response

@WebServlet("/hello") // Mapping the servlet to the "/hello" URL endpoint
public class SimpleServlet extends HttpServlet { // Creating the servlet by extending HttpServlet

    @Override // Overriding the method to handle GET requests
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException { // Method signature declaring potential exceptions

        response.setContentType("text/html"); // Instructing the client browser that the response is HTML

        PrintWriter out = response.getWriter(); // Getting the writer stream to send data to the client

        // Generating the HTML response line by line
        out.println("<html>"); // Starting HTML tag
        out.println("<head><title>My First Servlet</title></head>"); // Head and Title tags
        out.println("<body>"); // Starting Body tag
        out.println("<h1>Hello, Welcome to Java Servlets!</h1>"); // A heading element
        out.println("<p>This web page was dynamically generated by the server.</p>"); // A paragraph element
        out.println("</body>"); // Closing Body tag
        out.println("</html>"); // Closing HTML tag

        out.close(); // Closing the PrintWriter stream to complete the response
    }
}